language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mbarakaja
  password:
    secure: lCsbPvtrMqBzFq01i6SaLsnkoeIhQV8Iqz0n8+pqUPu6r26QKmMxIV6ZPr5ZzsJeaz8XlUgdbzwTK2xTM8NnUS/F7LFyy2hpQ+3JAXOMZdFLtpZ66CsU5EjP9uEpPdVYwBPcIdr4wceF02yiWSiuJ/vQ0/l24S7UwY62gKOG8ej6eNDZ2SwkHZcXy8xdWiDvzgGEWI79upMB0lFmfr/9OXMFlUoFwOO0HcnCZASLjx0yuXQCk2XgObDYBTb6nGLt3vFbso4NCClNCcVkDkyhTp15lT3Xq12Y7/F7CF6JMljC1TP80clD6QIW36FrP4DTBNo9+eroHy3jb02SNSlqj4dWOpROQH53zmMKB6sGTskBE+60bXVrJA+o9/ycnJJOkxb29Fh7rLWh/JH0AoE5nsYZs2Ekis94/agJltLA14AEc0ZIioemqNVp40xbfgPS14XZcEV0oFwO/y9qC+RlDcetIuswBKUuXgfxXQSlRpPspncEPdHCEu7gd81e36SX+7MJ0SUDNf0e/xICDZbu1AKqqY2jLgUil0sO9/YTder2rmXllMixz10D9cGODeWBzqQ3ri3RXiM6u8nEUSC6C61zH096CLnJbv1CweIp3Pj30qn5WgvlbLlV89IXZb6Si1t+TyZ1RAlsIElVL1m6n0N5GQY67wVnixEECiQMCSo=
  on:
    tags: true
    repo: mbarakaja/braulio
    python: 3.6
